version: '3'
services:
  postgres:
    build: ./pgsql
    container_name: api_pgsql
    volumes:
      - postgres_etl:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  es:
    image: elasticsearch:8.5.0
    container_name: api_es
    environment:
    - xpack.security.enabled=false
    - discovery.type=single-node
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    depends_on:
      - postgres
    volumes:
      - es_data:/usr/share/elasticsearch/data

  redis:
    image: redis:latest
    container_name: api_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  etl:
    build: ./etl
    container_name: api_etl
    environment:
    - ENV=prod
    depends_on:
      - postgres
      - es
      - redis

  nginx:
    image: nginx:latest
    container_name: api_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
    ports:
      - "8000:80"
    depends_on:
      - fastapi

  fastapi:
    build: ./src
    container_name: api_fastapi
    environment:
      - ENV=prod
      - ENV-FILE=/src/.env
    depends_on:
      - es
      - redis

volumes:
  postgres_etl:
  redis_data:
  es_data:
